const CONSTANTS = {};

CONSTANTS.SECOND = 1000;
CONSTANTS.MINUTE = CONSTANTS.SECOND * 60;
CONSTANTS.HOUR = CONSTANTS.MINUTE * 60;
CONSTANTS.DAY = CONSTANTS.HOUR * 24;

CONSTANTS.ALPHABET = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'];

CONSTANTS.DEFAULT_FAUCET_LIMITS = {
  UTXO: { max: 0.001, min: 0.000001 },
  STABLECOIN: { max: 25, min: 1 },
  EVM: { max: 0.01, min: 0.001 }
};

CONSTANTS.FAUCET_LIMITS = {
  BTC: CONSTANTS.DEFAULT_FAUCET_LIMITS.UTXO,
  BCH: CONSTANTS.DEFAULT_FAUCET_LIMITS.UTXO,
  DOGE: CONSTANTS.DEFAULT_FAUCET_LIMITS.UTXO,
  LTC: CONSTANTS.DEFAULT_FAUCET_LIMITS.UTXO,
  ETH: CONSTANTS.DEFAULT_FAUCET_LIMITS.EVM,
  USDC: CONSTANTS.DEFAULT_FAUCET_LIMITS.STABLECOIN,
  GUSD: CONSTANTS.DEFAULT_FAUCET_LIMITS.STABLECOIN,
  BUSD: CONSTANTS.DEFAULT_FAUCET_LIMITS.STABLECOIN,
  DAI: CONSTANTS.DEFAULT_FAUCET_LIMITS.STABLECOIN,
  PAX: CONSTANTS.DEFAULT_FAUCET_LIMITS.STABLECOIN,
  EUROC: CONSTANTS.DEFAULT_FAUCET_LIMITS.STABLECOIN,
  WBTC: CONSTANTS.DEFAULT_FAUCET_LIMITS.UTXO,
  SHIB: { max: 2000000, min: 100000 },
  APE: { max: 5, min: 1 },
  MATIC: CONSTANTS.DEFAULT_FAUCET_LIMITS.EVM
};

module.exports = CONSTANTS;
